### ISSUE TITLE
New syntax

### ISSUE THREAD

**Issue by ivansglazunov** [OSWS/OSWS-Stylus#6]
```styl
top 15px right
```
```css
* {
    top: 15px;
    right: 0;
}
```
---
```styl
margin horizontal 15px 2em
```
```css
* {
    margin-left: 15px;
    margin-right: 2em;
}
```
+ padding
